### ISSUE TITLE
Dark mode option not working in Windows

### ISSUE THREAD

**Issue by msarkrish** [leoafarias/sidekick#37] opened 2021-04-13 06:05 UTC
I tried to change dark mode, but it shows an error.
![Screenshot (109)](https://user-images.githubusercontent.com/45334931/114504290-45f40680-9c4c-11eb-9224-e43f9e060b7e.png)

**Comment by aguilaair** [comment] 2021-04-13 17:52
Hey! We've tried to replicate this issue but we have no problem changing the theme...
![image](https://user-images.githubusercontent.com/29983481/114598096-cc7f0700-9c91-11eb-8b25-3d4361c24f6b.png)

**Comment by msarkrish** [comment] 2021-04-13 18:33
@aguilaair I uploaded my screen recording.

https://user-images.githubusercontent.com/45334931/114602907-c0587100-9cb4-11eb-9716-ec8eecad6caf.mp4

**Comment by msarkrish** [comment] 2021-04-13 18:47
@aguilaair I'm Using Flutter v1.12.13+hotfix.8, so I could not run this project now.

**Comment by aguilaair** [comment] 2021-04-13 19:36
Ok, that's fine, let me see if I can send you over something to search for the error

**Comment by aguilaair** [comment] 2021-04-13 19:54
Hey, this will probably change nothing, but have you tried running it as an admin?

**Comment by leoafarias** [comment] 2021-04-13 19:58
@aguilaair I think that is it, I had mentioned in the settings, but its saving the fvm settings and it can't, You need admin in order to be able to manage the versions, and globals

**Comment by leoafarias** [comment] 2021-04-13 19:58
Another option is to just turn own `developer` mode on windows

**Comment by leoafarias** [comment] 2021-04-13 20:01
@msarkrish please let me know once you try the suggestion above

**Comment by msarkrish** [comment] 2021-04-14 07:02
@aguilaair @leoafarias I run the sidekick as administrator but still same exception showing.

**Comment by leoafarias** [comment] 2021-04-14 10:09
I think I know what the issue is, will push a fix on the next release

**Comment by msarkrish** [comment] 2021-04-14 14:24
Need sidekick release for this fix @leoafarias

**Comment by aguilaair** [comment] 2021-04-14 14:37
Hey, in the meantime here's a build: 
[Release.zip](https://github.com/leoafarias/sidekick/files/6311536/Release.zip)

**Comment by msarkrish** [comment] 2021-04-15 07:53
@leoafarias @aguilaair  Sidekick 0.0.1 also have this problem and advanced mode enable disable problem

**Comment by aguilaair** [comment] 2021-04-15 09:06
Ok, @leoafarias mind reopening this issue until it is IDd an fixed?

**Comment by leoafarias** [comment] 2021-04-15 10:10
The issue should not have been closed, I added closes instead of fixes on the merge comment so it closed automatically

**Comment by leoafarias** [comment] 2021-04-25 15:43
Issue should be fixed on 0.0.3

**Closed by leoafarias** 2021-04-25 15:43 UTC
Labels: bug
