### ISSUE TITLE
[Feature Request] Add Single Project without providing Directory for all Projects

### ISSUE THREAD

**Issue by crtl** [leoafarias/sidekick#62] opened 2021-05-05 07:12 UTC
TLDR: Users should be able to add single projects without parent directory.

After I downloaded the app this was the fist thing I saw and is pretty much a nogo for me.

Currently users select a project directory under which all projects are stored but in my opinion you should add projects by themselfes and not over detecting by a parent directory.

At the moment users are forced to use a specific directory structure so they may have to refactor their current one just to use the tool which is a downside for many.

**Comment by aguilaair** [comment] 2021-05-05 07:16
This is probably a duplicate of https://github.com/leoafarias/sidekick/issues/3 as long as it allows selecting a directory where the selected folder is already a flutter project

**Comment by crtl** [comment] 2021-05-05 07:26
@aguilaair I have seen #3 but its more about adding multiple root directories and not the ability to add a single project.

**Comment by leoafarias** [comment] 2021-06-10 12:15
This has been release on version 0.0.8

**Closed by leoafarias** 2021-06-10 12:15 UTC
Labels: enhancement
