### ISSUE TITLE
Overflow on some packages

### ISSUE THREAD

**Issue by aguilaair** [leoafarias/sidekick#46] opened 2021-04-15 09:28 UTC
![image](https://user-images.githubusercontent.com/29983481/114847137-abc3c800-9ddd-11eb-8a36-4d3f3d6ce343.png)
 

bug found on 0.0.1

**Comment by leoafarias** [comment] 2021-04-15 10:33
Resolved this issue... Seems an update was pushed to the package, and score switched to `pending`, which returns the score as null. The issue is fixed on that version after the cache expires, but I made a fix to make sure that does not happen again.

**Closed** 2021-04-15 11:46 UTC
